version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: invoice_db
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_password
      POSTGRES_DB: invoice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 